; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Generator pro version

#define MyAppName "Generator_DocForm"
#define MyAppVersion "1.2.3"
#define MyAppPublisher "Chrysystem"
#define MyAppExeName "Generator_Formation.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D0C76796-82EF-4332-8E59-79F63590E6FD}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Licence.txt
InfoBeforeFile=C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Info befor install.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=admin
OutputDir=C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\OutpuSetup
OutputBaseFilename=SetupGenerator-1.2.3
SetupIconFile=C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Setupinstaller\install_Icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Datas\*"; DestDir: "{app}\Datas"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\LogoTMH.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Setupinstaller\DocumentsCD\*"; DestDir: "{app}\Datas\"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: ShouldInstallCD
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Setupinstaller\DocumentsLB\*"; DestDir: "{app}\Datas\"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: ShouldInstallLB
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Setupinstaller\DocumentsPC\*"; DestDir: "{app}\Datas\"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: ShouldInstallPC
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Setupinstaller\DocumentsDR\*"; DestDir: "{app}\Datas\"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: ShouldInstallDR
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Setupinstaller\DocumentsXX\*"; DestDir: "{app}\Datas\"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: ShouldInstallXX
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\Setupinstaller\DocumentsAD\*"; DestDir: "{app}\Datas\"; Flags: ignoreversion recursesubdirs createallsubdirs; Check: ShouldInstallAD
Source: "C:\Users\frchdes\OneDrive - Toyota Material Handling Europe\Dokument\00-Documents_AE\Documents A_E\00-Dev\Generator\logo-Toyota-Solo.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files



[Code]

var
  TemplatePage: TWizardPage;
  SelectedTemplate: String;
  TemplateCombo: TComboBox;

procedure InitializeWizard;
begin
  TemplatePage := CreateCustomPage(wpSelectDir, 'Choix du template', 'Sélectionnez un template à installer');
  TemplateCombo := TComboBox.Create(TemplatePage.Surface);
  TemplateCombo.Parent := TemplatePage.Surface;
  TemplateCombo.Left := 10;
  TemplateCombo.Top := 10;
  TemplateCombo.Width := 200;
  TemplateCombo.Items.Add('DocumentsAD');
  TemplateCombo.Items.Add('DocumentsCD');
  TemplateCombo.Items.Add('DocumentsLB');
  TemplateCombo.Items.Add('DocumentsPC');
  TemplateCombo.Items.Add('DocumentsDR');
  TemplateCombo.Items.Add('DocumentsXX');
  TemplateCombo.ItemIndex := 0;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
    SelectedTemplate := TemplateCombo.Items[TemplateCombo.ItemIndex];
end;

function ShouldInstallCD: Boolean;
begin
  Result := SelectedTemplate = 'DocumentsCD';
end;

function ShouldInstallLB: Boolean;
begin
  Result := SelectedTemplate = 'DocumentsLB';
end;

function ShouldInstallPC: Boolean;
begin
  Result := SelectedTemplate = 'DocumentsPC';
end;

function ShouldInstallDR: Boolean;
begin
  Result := SelectedTemplate = 'DocumentsDR';
end;

function ShouldInstallAD: Boolean;
begin
  Result := SelectedTemplate = 'DocumentsAD';
end;

function ShouldInstallXX: Boolean;
begin
  Result := SelectedTemplate = 'DocumentsXX';
end;

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

